apiVersion: v1
kind: PersistentVolumeClaim

metadata:
  name: kubeflow-pvc
  namespace: kubeflow

spec:
  accessModes:
    - ReadWriteOnce

  storageClassName: manual

  resources:
    requests:
      storage: 20Gi